// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/client/service.proto

package nighthawk_client

import (
	"context"
	reflect "reflect"
	sync "sync"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	status "google.golang.org/genproto/googleapis/rpc/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status1 "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *CommandLineOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_api_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetOptions() *CommandLineOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// TODO(oschaaf): Not implemented yet.
type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_client_service_proto_rawDescGZIP(), []int{1}
}

// TODO(oschaaf): Not implemented yet.
type CancellationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancellationRequest) Reset() {
	*x = CancellationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancellationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancellationRequest) ProtoMessage() {}

func (x *CancellationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancellationRequest.ProtoReflect.Descriptor instead.
func (*CancellationRequest) Descriptor() ([]byte, []int) {
	return file_api_client_service_proto_rawDescGZIP(), []int{2}
}

type ExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to CommandSpecificOptions:
	//	*ExecutionRequest_StartRequest
	//	*ExecutionRequest_UpdateRequest
	//	*ExecutionRequest_CancellationRequest
	CommandSpecificOptions isExecutionRequest_CommandSpecificOptions `protobuf_oneof:"command_specific_options"`
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_api_client_service_proto_rawDescGZIP(), []int{3}
}

func (m *ExecutionRequest) GetCommandSpecificOptions() isExecutionRequest_CommandSpecificOptions {
	if m != nil {
		return m.CommandSpecificOptions
	}
	return nil
}

func (x *ExecutionRequest) GetStartRequest() *StartRequest {
	if x, ok := x.GetCommandSpecificOptions().(*ExecutionRequest_StartRequest); ok {
		return x.StartRequest
	}
	return nil
}

func (x *ExecutionRequest) GetUpdateRequest() *UpdateRequest {
	if x, ok := x.GetCommandSpecificOptions().(*ExecutionRequest_UpdateRequest); ok {
		return x.UpdateRequest
	}
	return nil
}

func (x *ExecutionRequest) GetCancellationRequest() *CancellationRequest {
	if x, ok := x.GetCommandSpecificOptions().(*ExecutionRequest_CancellationRequest); ok {
		return x.CancellationRequest
	}
	return nil
}

type isExecutionRequest_CommandSpecificOptions interface {
	isExecutionRequest_CommandSpecificOptions()
}

type ExecutionRequest_StartRequest struct {
	StartRequest *StartRequest `protobuf:"bytes,1,opt,name=start_request,json=startRequest,proto3,oneof"`
}

type ExecutionRequest_UpdateRequest struct {
	UpdateRequest *UpdateRequest `protobuf:"bytes,2,opt,name=update_request,json=updateRequest,proto3,oneof"`
}

type ExecutionRequest_CancellationRequest struct {
	CancellationRequest *CancellationRequest `protobuf:"bytes,3,opt,name=cancellation_request,json=cancellationRequest,proto3,oneof"`
}

func (*ExecutionRequest_StartRequest) isExecutionRequest_CommandSpecificOptions() {}

func (*ExecutionRequest_UpdateRequest) isExecutionRequest_CommandSpecificOptions() {}

func (*ExecutionRequest_CancellationRequest) isExecutionRequest_CommandSpecificOptions() {}

type ExecutionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output      *Output        `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ErrorDetail *status.Status `protobuf:"bytes,7,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	// Opaque identifier for lookup purposes. This will be taken from CommandLineOptions if set,
	// if it is not set there it will be auto-generated. The format used for auto-generated
	// identifiers may change at any time.
	ExecutionId string `protobuf:"bytes,8,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_api_client_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionResponse) GetOutput() *Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecutionResponse) GetErrorDetail() *status.Status {
	if x != nil {
		return x.ErrorDetail
	}
	return nil
}

func (x *ExecutionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

var File_api_client_service_proto protoreflect.FileDescriptor

var file_api_client_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6e, 0x69, 0x67, 0x68,
	0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3e, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x6e,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa0, 0x02, 0x0a, 0x10, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45,
	0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77,
	0x6b, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x5a, 0x0a, 0x14, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x13, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x1f, 0x0a, 0x18, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x5f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x03, 0xf8, 0x42, 0x01, 0x22, 0x9f, 0x01, 0x0a,
	0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x35, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0x74,
	0x0a, 0x10, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x22, 0x2e, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x61, 0x77,
	0x6b, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6e, 0x69, 0x67, 0x68,
	0x74, 0x68, 0x61, 0x77, 0x6b, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_client_service_proto_rawDescOnce sync.Once
	file_api_client_service_proto_rawDescData = file_api_client_service_proto_rawDesc
)

func file_api_client_service_proto_rawDescGZIP() []byte {
	file_api_client_service_proto_rawDescOnce.Do(func() {
		file_api_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_client_service_proto_rawDescData)
	})
	return file_api_client_service_proto_rawDescData
}

var file_api_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_client_service_proto_goTypes = []interface{}{
	(*StartRequest)(nil),        // 0: nighthawk.client.StartRequest
	(*UpdateRequest)(nil),       // 1: nighthawk.client.UpdateRequest
	(*CancellationRequest)(nil), // 2: nighthawk.client.CancellationRequest
	(*ExecutionRequest)(nil),    // 3: nighthawk.client.ExecutionRequest
	(*ExecutionResponse)(nil),   // 4: nighthawk.client.ExecutionResponse
	(*CommandLineOptions)(nil),  // 5: nighthawk.client.CommandLineOptions
	(*Output)(nil),              // 6: nighthawk.client.Output
	(*status.Status)(nil),       // 7: google.rpc.Status
}
var file_api_client_service_proto_depIdxs = []int32{
	5, // 0: nighthawk.client.StartRequest.options:type_name -> nighthawk.client.CommandLineOptions
	0, // 1: nighthawk.client.ExecutionRequest.start_request:type_name -> nighthawk.client.StartRequest
	1, // 2: nighthawk.client.ExecutionRequest.update_request:type_name -> nighthawk.client.UpdateRequest
	2, // 3: nighthawk.client.ExecutionRequest.cancellation_request:type_name -> nighthawk.client.CancellationRequest
	6, // 4: nighthawk.client.ExecutionResponse.output:type_name -> nighthawk.client.Output
	7, // 5: nighthawk.client.ExecutionResponse.error_detail:type_name -> google.rpc.Status
	3, // 6: nighthawk.client.NighthawkService.ExecutionStream:input_type -> nighthawk.client.ExecutionRequest
	4, // 7: nighthawk.client.NighthawkService.ExecutionStream:output_type -> nighthawk.client.ExecutionResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_client_service_proto_init() }
func file_api_client_service_proto_init() {
	if File_api_client_service_proto != nil {
		return
	}
	file_api_client_options_proto_init()
	file_api_client_output_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_client_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancellationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_client_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ExecutionRequest_StartRequest)(nil),
		(*ExecutionRequest_UpdateRequest)(nil),
		(*ExecutionRequest_CancellationRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_client_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_client_service_proto_goTypes,
		DependencyIndexes: file_api_client_service_proto_depIdxs,
		MessageInfos:      file_api_client_service_proto_msgTypes,
	}.Build()
	File_api_client_service_proto = out.File
	file_api_client_service_proto_rawDesc = nil
	file_api_client_service_proto_goTypes = nil
	file_api_client_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NighthawkServiceClient is the client API for NighthawkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NighthawkServiceClient interface {
	//  Accepts a stream of ExecutionRequests, which can be used to initiate, update, or cancel a
	//  test. Returns a stream of ExecutionResponse objects which will contain results for all
	//  Nighthawk runs.
	ExecutionStream(ctx context.Context, opts ...grpc.CallOption) (NighthawkService_ExecutionStreamClient, error)
}

type nighthawkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNighthawkServiceClient(cc grpc.ClientConnInterface) NighthawkServiceClient {
	return &nighthawkServiceClient{cc}
}

func (c *nighthawkServiceClient) ExecutionStream(ctx context.Context, opts ...grpc.CallOption) (NighthawkService_ExecutionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NighthawkService_serviceDesc.Streams[0], "/nighthawk.client.NighthawkService/ExecutionStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &nighthawkServiceExecutionStreamClient{stream}
	return x, nil
}

type NighthawkService_ExecutionStreamClient interface {
	Send(*ExecutionRequest) error
	Recv() (*ExecutionResponse, error)
	grpc.ClientStream
}

type nighthawkServiceExecutionStreamClient struct {
	grpc.ClientStream
}

func (x *nighthawkServiceExecutionStreamClient) Send(m *ExecutionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nighthawkServiceExecutionStreamClient) Recv() (*ExecutionResponse, error) {
	m := new(ExecutionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NighthawkServiceServer is the server API for NighthawkService service.
type NighthawkServiceServer interface {
	//  Accepts a stream of ExecutionRequests, which can be used to initiate, update, or cancel a
	//  test. Returns a stream of ExecutionResponse objects which will contain results for all
	//  Nighthawk runs.
	ExecutionStream(NighthawkService_ExecutionStreamServer) error
}

// UnimplementedNighthawkServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNighthawkServiceServer struct {
}

func (*UnimplementedNighthawkServiceServer) ExecutionStream(NighthawkService_ExecutionStreamServer) error {
	return status1.Errorf(codes.Unimplemented, "method ExecutionStream not implemented")
}

func RegisterNighthawkServiceServer(s *grpc.Server, srv NighthawkServiceServer) {
	s.RegisterService(&_NighthawkService_serviceDesc, srv)
}

func _NighthawkService_ExecutionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NighthawkServiceServer).ExecutionStream(&nighthawkServiceExecutionStreamServer{stream})
}

type NighthawkService_ExecutionStreamServer interface {
	Send(*ExecutionResponse) error
	Recv() (*ExecutionRequest, error)
	grpc.ServerStream
}

type nighthawkServiceExecutionStreamServer struct {
	grpc.ServerStream
}

func (x *nighthawkServiceExecutionStreamServer) Send(m *ExecutionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nighthawkServiceExecutionStreamServer) Recv() (*ExecutionRequest, error) {
	m := new(ExecutionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NighthawkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nighthawk.client.NighthawkService",
	HandlerType: (*NighthawkServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecutionStream",
			Handler:       _NighthawkService_ExecutionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
